export enum Racas {
  Anao = 'Anão',
  Dahllan = 'Dahllan',
  Elfo = 'Elfo',
  Goblin = 'Goblin',
  Humano = 'Humano',
  Lefou = 'Lefou',
  Minotauro = 'Minotauro',
  Qareen = 'Qareen',
  Golem = 'Golem',
  Hynne = 'Hynne',
  Kliren = 'Kliren',
  Medusa = 'Medusa',
  Osteon = 'Osteon',
  Sílfide = 'Sílfide',
  Suraggel = 'Suraggel',
  Tritao = 'Tritao',
  Trog = 'Trog',
}
